#!/usr/bin/env bash

log="/root/scc-ansible.log"

if [[ ! -f "$log" ]]; then
  printf "${MAGENTA}%-20s:${NC}${YELLOW}%s - ${NC}${YELLOW}%s${NC}\n" \
    "Ansible Log Check" "!!ATTN!!" \
    "Ansible was not run; log is not present."
  exit 1
fi

last_change_line=$(grep 'changed' "$log" | tail -n 1)
failed_count=$(grep -oE 'failed=[0-9]+' <<< "$last_change_line" | cut -d= -f2)

if [[ "${failed_count:-0}" -gt 0 ]]; then
  printf "${MAGENTA}%-20s:${NC}${RED}%s - ${NC}${YELLOW}%s${NC}\n" \
    "Ansible Log Check" "!!BAD!!" \
    "Ansible log indicates failures."
else
  printf "${MAGENTA}%-20s:${NC}${GREEN}%s - ${NC}${YELLOW}%s${NC}\n" \
    "Ansible Log Check" "!!GOOD!!" \
    "Ansible log indicates success."
fi


if semanage fcontext -C -l | grep -q ':ssh_home_t:'; then
    printf "${MAGENTA}%-20s:${NC}${GREEN}%s- ${NC}${YELLOW}%s${NC}\n" "Custom Context Check (ssh_home_t)" "!!GOOD!!" "Custom context ssh_home_t exists on system"
else
    printf "${MAGENTA}%-20s:${NC}${RED}%s - ${NC}${YELLOW}%s${NC}\n" "Custom Context Check (ssh_home_t)" "!!BAD!!" "The custom context ssh_home_t is not on system"
fi
